### ISSUE TITLE
Map the Web pages into the source tree

### ISSUE THREAD

**Issue by navneetkarnani** [GeertjanWielenga/SpringBootTools4NetBeans#3]
When building a SpringBoot application, the web pages sit in the resources directory. The default maven structure for this kind of application does not add a "resources" directory hence there is no mapping shown. Netbeans has a great way to work with HTML5 and Single Page Applications, including auto complete for Javascript. But all that is not currently configured correctly for Springboot applications. 

Can you set up the project correctly such that Netbeans' power is harnessed when working with the project ?

**Comment by geertjanw** [comment]
Need you to provide a ZIP file containing a project showing what you mean because I don't get it.

**Comment by navneetkarnani** [comment]
I am attaching two files with this. 
- demo.zip , as generated by start.spring.io but added a html file in the static folder
- Screenshot of the folder view

Notice that there is not "web" folder in the screenshot, but there are "resources" and "other"
vs in the DemoWeb project (created using Netbeans new project Java Web) where the web folder shows up as "Web Pages"

The first level showing up of the static folder can help with making working with Single Page Applications in Spring boot, where there is a single pom, much easier.

![screen shot 2016-03-04 at 12 54 43 pm](https://cloud.githubusercontent.com/assets/2557648/13520682/671f6a2e-e208-11e5-82e5-88676fafd6d5.png)
(https://cloud.githubusercontent.com/assets/2557648/13520560/6010ddb8-e207-11e5-83ea-1139311b5e32.png)
[demo.zip](https://github.com/GeertjanWielenga/SpringBootTools4NetBeans/files/158255/demo.zip)

**Comment by geertjanw** [comment]
So what you're saying is that start.spring.io should be integrated into NetBeans? If that's what you're saying, I agree, and am working on it.

**Comment by navneetkarnani** [comment]
I am saying that the project that we get from start.spring.io should have a
project tree just like the one generated by  Java Web

**Comment by GeertjanWielenga** [comment]
The project you get from start.spring.io is a Maven project. In NetBeans IDE, it looks like any other Maven project.

**Comment by navneetkarnani** [comment]
I understand that. This is the reason its a enhancement request for SpringBoot projects :)

**Comment by GeertjanWielenga** [comment]
So, shouldn't you file an issue with SpringBoot? Instead of filing an issue with the NetBeans plugin that supports SpringBoot?

**Comment by navneetkarnani** [comment]
This is a Netbeans specific behavior. The SpringBoot project complies correctly with Maven. Just like Spring Toolsuite (STS) plugin handles all the Spring and SpringBoot specific behavior ( eg. the run button there handles the correct maven target to call ), the SpringBoot plugin in Netbeans should be the right place. 

My ask may be a little above the board, but I think it brings value to the workflow. After all, we want Netbeans to be the best development platform.

**Comment by GeertjanWielenga** [comment]
I just don't get it, sorry. Let's use e-mail -- geertjan.wielenga@oracle.com. Try and make the e-mail really short and clear about what it is that you want.
